# Generated by Django 5.1 on 2024-09-26 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_landowner',
            field=models.BooleanField(default=False, help_text='Check this if the user is a landowner, otherwise they will be a leasee.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and include both letters and numbers.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')]),
        ),
    ]
