# Generated by Django 5.1 on 2024-10-03 04:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image of the room.', max_length=255, null=True, verbose_name='room_image'),
        ),
    ]
