# Generated by Django 5.1 on 2024-10-23 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_deposits', to='rooms.landlord'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='leasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leasee_deposits', to='rooms.leasee'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_deposits', to='rooms.room'),
        ),
    ]
