# Generated by Django 5.1 on 2024-10-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_landowner',
            field=models.BooleanField(default=False, help_text='Check if the user is a landowner; otherwise, they are a lessee.'),
        ),
    ]
