# Generated by Django 5.1 on 2024-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_landlord_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='company_name',
        ),
        migrations.AddField(
            model_name='leasee',
            name='location_url',
            field=models.URLField(blank=True, help_text='URL for the map location of the renter', max_length=500, null=True),
        ),
    ]
