# Generated by Django 5.1 on 2024-10-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_district_room_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasee',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='leasee',
            name='reviews',
        ),
    ]
