# Generated by Django 5.1 on 2024-10-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_leasee_location_url_remove_leasee_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='district',
            field=models.CharField(default='Dhankuta', help_text='District name', max_length=255),
        ),
        migrations.AddField(
            model_name='landlord',
            name='province',
            field=models.CharField(choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], default='Province 1', help_text='Select a province', max_length=255),
        ),
        migrations.AddField(
            model_name='leasee',
            name='district',
            field=models.CharField(default='Dhankuta', help_text='District name', max_length=255),
        ),
        migrations.AddField(
            model_name='leasee',
            name='province',
            field=models.CharField(choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], default='Province 1', help_text='Select a province', max_length=255),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='address',
            field=models.CharField(help_text='Full address of the room.', max_length=255),
        ),
        migrations.AlterField(
            model_name='leasee',
            name='address',
            field=models.CharField(help_text='Full address of the room.', max_length=255),
        ),
    ]
