# Generated by Django 5.1 on 2024-09-26 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_landlord_sub_address_leasee_sub_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, help_text='Full address of the room.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='location_url',
            field=models.URLField(blank=True, help_text='URL for the map location of the room.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='sub_address',
            field=models.CharField(blank=True, help_text='Street name or specific sub-address.', max_length=255, null=True),
        ),
    ]
