# Generated by Django 5.1 on 2024-09-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_room_location_room_address_room_location_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the deposit required.', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', help_text='Status of the deposit payment.', max_length=10)),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('leasee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='rooms.leasee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='rooms.room')),
            ],
        ),
    ]
