# Generated by Django 5.1 on 2024-10-25 09:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_landlord_district_landlord_province_leasee_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image of the room.', max_length=255, null=True, verbose_name='profile_landlord_image'),
        ),
        migrations.AddField(
            model_name='leasee',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image of the room.', max_length=255, null=True, verbose_name='profile_leasee_image'),
        ),
    ]
