# Generated by Django 5.1 on 2024-10-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_landlord_profile_image_leasee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='district',
            field=models.CharField(blank=True, help_text='District name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='province',
            field=models.CharField(blank=True, choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], help_text='Select a province', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leasee',
            name='district',
            field=models.CharField(blank=True, help_text='District name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leasee',
            name='province',
            field=models.CharField(blank=True, choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], help_text='Select a province', max_length=255, null=True),
        ),
    ]
