# Generated by Django 5.1 on 2024-10-02 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_notification_visitrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location_url',
            field=models.URLField(help_text='URL for the map location of the room.', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='sub_address',
            field=models.CharField(default=django.utils.timezone.now, help_text='Street name or specific sub-address.', max_length=255),
            preserve_default=False,
        ),
    ]
