# Generated by Django 5.1 on 2024-10-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_landlord_district_alter_landlord_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='address',
            field=models.CharField(blank=True, help_text='Full address of the room.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leasee',
            name='address',
            field=models.CharField(blank=True, help_text='Full address of the room.', max_length=255, null=True),
        ),
    ]
