# Generated by Django 5.1 on 2024-10-29 04:18

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_roomcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_image', cloudinary.models.CloudinaryField(help_text='Upload an identity document (e.g., citizenship, college ID).', max_length=255, verbose_name='identity_images/')),
                ('is_verified', models.BooleanField(default=False, help_text="Indicates whether the user's identity has been verified.")),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
