# Generated by Django 5.1 on 2024-10-29 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_identityverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='rooms.room'),
        ),
    ]
