# Generated by Django 5.1 on 2024-11-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_alter_identityverification_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='rooms.room'),
        ),
    ]
