LOCATION_CHOICES = [
    ('Bhaktapur Durbar Square', 'Bhaktapur Durbar Square'),
    ('Taumadhi Square', 'Taumadhi Square'),
    ('Pottery Square', 'Pottery Square'),
    ('Dattatreya Square', 'Dattatreya Square'),
    ('Nagarkot', 'Nagarkot'),
    ('Changu Narayan', 'Changu Narayan'),
    ('Siddha Pokhari', 'Siddha Pokhari'),
    ('Bhairavnath Temple', 'Bhairavnath Temple'),
    ('Nyatapola Temple', 'Nyatapola Temple'),
    ('55 Windows Palace', '55 Windows Palace'),
    
    # Kathmandu
    ('Thamel', 'Thamel'),
    ('Durbar Square', 'Durbar Square'),
    ('Boudhanath', 'Boudhanath'),
    ('Pashupatinath', 'Pashupatinath'),
    ('Swayambhunath', 'Swayambhunath'),
    ('Kirtipur', 'Kirtipur'),
    ('Budhanilkantha', 'Budhanilkantha'),
    ('Kalimati', 'Kalimati'),
    ('Maitidevi', 'Maitidevi'),
    ('Gaushala', 'Gaushala'),
    ('Chabahil', 'Chabahil'),
    ('Maitighar', 'Maitighar'),
    ('New Baneswor', 'New Baneswor'),
    ('Old Baneswor', 'Old Baneswor'),
    ('Sinamangal', 'Sinamangal'),
    ('Kalopul', 'Kalopul'),
    ('Dhobighat', 'Dhobighat'),
    ('Jawalakhel', 'Jawalakhel'),
    ('Kupondole', 'Kupondole'),
    ('Lagankhel', 'Lagankhel'),
    ('Sanepa', 'Sanepa'),
    ('Bagbazar', 'Bagbazar'),
    ('Putalisadak', 'Putalisadak'),
    ('Kamalpokhari', 'Kamalpokhari'),
    ('Naxal', 'Naxal'),
    ('Baluwatar', 'Baluwatar'),
    ('Maharajgunj', 'Maharajgunj'),
    ('Basundhara', 'Basundhara'),
    ('Dhapasi', 'Dhapasi'),
    ('Buddha Nagar', 'Buddha Nagar'),
    ('Kalanki', 'Kalanki'),
    ('Teku', 'Teku'),
    ('Tripureshwor', 'Tripureshwor'),
    ('Sitapaila', 'Sitapaila'),
    ('Swoyambhu', 'Swoyambhu'),
    ('Balkhu', 'Balkhu'),
    ('Kuleshwor', 'Kuleshwor'),
    ('Chakupat', 'Chakupat'),
    ('Jadibuti', 'Jadibuti'),
    
    # Lalitpur
    ('Patan Durbar Square', 'Patan Durbar Square'),
    ('Ashokan Stupas', 'Ashokan Stupas'),
    ('Mahaboudha Temple', 'Mahaboudha Temple'),
    ('Taleju Temple', 'Taleju Temple'),
    ('Bhimsen Tower', 'Bhimsen Tower'),
    ('Hiranya Varna Mahavihar', 'Hiranya Varna Mahavihar'),
    ('Jagat Narayan Temple', 'Jagat Narayan Temple'),
    ('Chabahil Stupa', 'Chabahil Stupa'),
    ('Tusha Hiti', 'Tusha Hiti'),
    ('Pulchowk', 'Pulchowk'),
    ('Jawalakhel', 'Jawalakhel'),
    ('Kupondole', 'Kupondole'),
    ('Lagankhel', 'Lagankhel'),
    ('Sanepa', 'Sanepa'),
    ('Balkumari', 'Balkumari'),
    ('Bhanimandal', 'Bhanimandal'),
    ('Ekantakuna', 'Ekantakuna'),
    ('Satdobato', 'Satdobato'),
    ('Imadol', 'Imadol'),
    ('Bhaisepati', 'Bhaisepati'),
]


